# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tda-silv <tda-silv@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/08 07:04:08 by tda-silv          #+#    #+#              #
#    Updated: 2022/06/20 16:01:27 by tda-silv         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC += ./sort_five_double/sfd_a/sfd_if_sorted_a.c \
	   ./sort_five_double/sfd_a/sfd_make_all_oper_a.c \
	   ./sort_five_double/sfd_a/sfd_sort_first_five_a.c \
	   ./sort_five_double/sfd_b/sfd_if_sorted_b.c \
	   ./sort_five_double/sfd_b/sfd_make_all_oper_b.c \
	   ./sort_five_double/sfd_b/sfd_sort_first_five_b.c \
	   ./sort_five_double/sort_five_double.c \
	   ./sort_five_double/while_for_sfd.c \

all: $(SRC)

