# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tda-silv <tda-silv@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/01 12:03:32 by tda-silv          #+#    #+#              #
#    Updated: 2022/06/10 13:24:35 by tda-silv         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC += ./smart_sort_five_b/t_list_int/tli_new.c \
	   ./smart_sort_five_b/t_list_int/tli_setup_a_five.c \
	   ./smart_sort_five_b/t_list_int/tli_setup_a_ten.c \
	   ./smart_sort_five_b/t_list_int/tli_setup_b_five.c \
	   ./smart_sort_five_b/t_list_int/tli_setup_b_ten.c \
	   ./smart_sort_five_b/t_list_int/tli_setup_b_half_a.c \
	   ./smart_sort_five_b/t_list_int/tli_add_back.c \
	   ./smart_sort_five_b/t_list_int/tli_size.c \
	   ./smart_sort_five_b/t_list_int/tli_last.c \
	   ./smart_sort_five_b/t_list_int/tli_clear.c \
	   ./smart_sort_five_b/t_list_int/tli_clear_one.c \
	   ./smart_sort_five_b/t_list_int/find_pos_max_tli.c \
	   ./smart_sort_five_b/t_list_int/find_pos_min_tli.c \

all: $(SRC)
