# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tda-silv <tda-silv@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/01 12:03:32 by tda-silv          #+#    #+#              #
#    Updated: 2022/06/07 07:22:26 by tda-silv         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC += ./t_list_int/tli_new.c \
	   ./t_list_int/tli_add_back.c \
	   ./t_list_int/tli_size.c \
	   ./t_list_int/tli_last.c \
	   ./t_list_int/tli_clear.c \
	   ./t_list_int/find_pos_max_tli.c \

all: $(SRC)
