# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tda-silv <tda-silv@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/01 12:03:32 by tda-silv          #+#    #+#              #
#    Updated: 2022/06/01 23:47:29 by tda-silv         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC += ./sort_five/sort_five.c \
	   ./sort_five/if_sorted.c \
	   ./sort_five/make_all_oper.c \
	   ./sort_five/ascending_order_tab.c \
	   ./sort_five/dup_tab.c \
	   ./sort_five/double_lst/dl_add_back.c \
	   ./sort_five/double_lst/dl_last.c \
	   ./sort_five/double_lst/dl_new.c \
	   ./sort_five/double_lst/sl_add_back.c \
	   ./sort_five/double_lst/sl_last.c \
	   ./sort_five/double_lst/sl_new.c \
	   ./sort_five/double_lst/sl_link.c \
	   ./sort_five/double_lst/dl_clear.c \
	   ./sort_five/double_lst/sl_int_clear.c \
	   ./sort_five/operations_dupp_tab/sa_dt.c \
	   ./sort_five/operations_dupp_tab/ra_dt.c \
	   ./sort_five/operations_dupp_tab/rra_dt.c \
	   ./sort_five/operations_on_tab/sa_ot.c \
	   ./sort_five/operations_on_tab/ra_ot.c \
	   ./sort_five/operations_on_tab/rra_ot.c \

all: $(SRC)
