# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tda-silv <tda-silv@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/01 12:03:32 by tda-silv          #+#    #+#              #
#    Updated: 2022/06/08 08:57:09 by tda-silv         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC =	./operation/sa.c \
		./operation/sb.c \
		./operation/ss.c \
		./operation/pa.c \
		./operation/pb.c \
		./operation/ra.c \
		./operation/rb.c \
		./operation/rr.c \
		./operation/rra.c \
		./operation/rrb.c \
		./operation/rrr.c \
		./operation/oper_double/od_sa.c \
		./operation/oper_double/od_sb.c \
		./operation/oper_double/od_ra.c \
		./operation/oper_double/od_rb.c \
		./operation/oper_double/od_rra.c \
		./operation/oper_double/od_rrb.c \

all: $(SRC)
