# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tda-silv <tda-silv@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/06/07 12:18:24 by tda-silv          #+#    #+#              #
#    Updated: 2022/06/10 12:26:44 by tda-silv         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC += ./smart_sort_five_b/choice_better_give_nb.c \
	   ./smart_sort_five_b/choice_better_give_nb_b.c \
	   ./smart_sort_five_b/choice_better.c \
	   ./smart_sort_five_b/choice_better_b.c \
	   ./smart_sort_five_b/five_smaller_a.c \
	   ./smart_sort_five_b/five_smaller_b.c \
	   ./smart_sort_five_b/pos_in_stack.c \
	   ./smart_sort_five_b/rotate_choice.c \
	   ./smart_sort_five_b/up_smaller_tli_b.c \

all: $(SRC)
